//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Sync_Pack.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CellToSapPackSoap", Namespace="http://tempuri.org/")]
    public partial class CellToSapPack : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendCellDataOfLsmesToSapPackOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsExceptionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CellToSapPack() {
            this.Url = global::Sync_Pack.Properties.Settings.Default.Sync_Pack_WebReference_CellToSapPack;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendCellDataOfLsmesToSapPackCompletedEventHandler SendCellDataOfLsmesToSapPackCompleted;
        
        /// <remarks/>
        public event IsExceptionCompletedEventHandler IsExceptionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendCellDataOfLsmesToSapPack", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendCellDataOfLsmesToSapPack(string info) {
            object[] results = this.Invoke("SendCellDataOfLsmesToSapPack", new object[] {
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendCellDataOfLsmesToSapPackAsync(string info) {
            this.SendCellDataOfLsmesToSapPackAsync(info, null);
        }
        
        /// <remarks/>
        public void SendCellDataOfLsmesToSapPackAsync(string info, object userState) {
            if ((this.SendCellDataOfLsmesToSapPackOperationCompleted == null)) {
                this.SendCellDataOfLsmesToSapPackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCellDataOfLsmesToSapPackOperationCompleted);
            }
            this.InvokeAsync("SendCellDataOfLsmesToSapPack", new object[] {
                        info}, this.SendCellDataOfLsmesToSapPackOperationCompleted, userState);
        }
        
        private void OnSendCellDataOfLsmesToSapPackOperationCompleted(object arg) {
            if ((this.SendCellDataOfLsmesToSapPackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCellDataOfLsmesToSapPackCompleted(this, new SendCellDataOfLsmesToSapPackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsException", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IsException(string info) {
            object[] results = this.Invoke("IsException", new object[] {
                        info});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IsExceptionAsync(string info) {
            this.IsExceptionAsync(info, null);
        }
        
        /// <remarks/>
        public void IsExceptionAsync(string info, object userState) {
            if ((this.IsExceptionOperationCompleted == null)) {
                this.IsExceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsExceptionOperationCompleted);
            }
            this.InvokeAsync("IsException", new object[] {
                        info}, this.IsExceptionOperationCompleted, userState);
        }
        
        private void OnIsExceptionOperationCompleted(object arg) {
            if ((this.IsExceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsExceptionCompleted(this, new IsExceptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SendCellDataOfLsmesToSapPackCompletedEventHandler(object sender, SendCellDataOfLsmesToSapPackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendCellDataOfLsmesToSapPackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendCellDataOfLsmesToSapPackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsExceptionCompletedEventHandler(object sender, IsExceptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsExceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsExceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591